print('Operações basica de dois valores.')
num1 = input('Digite o n°1: ')
num2 = input('Digite o n°2: ')
soma = int (num1) + int (num2)
sub = int (num1) + int (num2)
div = int (num1) + int (num2)
mult = int (num1) + int (num2)
print('A soma é: ',str (soma))
print('A subtração é: ',str(sub))
print('A multiplicação é: ',str(mult))
print('A divisão é: ',str(div))
