nome = input('Qual é o seu nome: ')
idade = input ('Qual é a sua idade: ')
peso = input('Digite o seu peso: ')
print ('Olá ',nome,'você disse que tem ',idade,'correto?')
print ('E você tem',peso,' kg')
